### ISSUE TITLE
Integer/Float/Boolean parameter settings are invalid

### ISSUE THREAD

**Issue by haitunxiaomo** [Esri/pyprt-examples#82]
Call the RPK file to generate the model in the following way:
![1690768560546](https://github.com/Esri/pyprt-examples/assets/8519144/a2469716-fa34-4370-aa50-f2391e343844)

If the shape_attributes parameter is set as follows, the generated model does not set the height according to the height parameter:
`shape_attributes ={
"height":100
}`

However, if height is set to a string, height is valid：
`shape_attributes ={
"height":"100"
}`

Float type data is also the same problem

**Comment by mistafunk** [comment]
Hi,

it should work when you write `100.0`. Or is this what you mean with "float ype data is the same problem"?

**Comment by haitunxiaomo** [comment]
> Hi,
> 
> it should work when you write `100.0`. Or is this what you mean with "float ype data is the same problem"?
it doesn't work when I set the type to Integer or Float。

**Comment by haitunxiaomo** [comment]
it doesn't work when I set the type to Integer or Float。

**Comment by mistafunk** [comment]
> it doesn't work when I set the type to Integer or Float。

how exactly did you set the type?

did you try like this?
`shape_attributes ={ "height": 100.0 }`

how is you `height` attribute defined in CGA?

**Comment by haitunxiaomo** [comment]
`version "2022.0"

#Building Attributes

#attr Height="50"
attr Height=50

@StartRule
Lot-->
	extrude(Height)
	#extrude(rint(float(Height)))`

set
` shape_attributes ={ "height": 100.0 }`
the result is ok.
set
` shape_attributes ={ "height": 100 }`
it don`t work

**Comment by mistafunk** [comment]
Ok, this is expected behavior of the current PyPRT implementation (`100` is an integer and not recognized in this case, `100.0` is a float/double/number and recognized as the matching attribute).

However, I am surprised that this works at all with the case-mismatch between `Height` (in your CGA) and `height` in your Python dict. Would you mind checking that you indeed see the expected value for Height in the CGA (you could use CGA `print` and then look at the `CGAPrint.txt` file in the output directory)?

**Comment by mistafunk** [comment]
I'm taking the liberty to close this one due to inactivity - feel free to reopen in case there is still a problem!
